accounts/urls.py
from django.urls import path
from .views import user_register, mitra_register, CustomLoginView
from django.contrib.auth.views import LogoutView


app_name = 'accounts'
urlpatterns = [
    path('login/user/', CustomLoginView.as_view(extra_context={'title': 'Login User'}), name='login_user'),
    path('login/mitra/', CustomLoginView.as_view(extra_context={'title': 'Login Mitra'}), name='login_mitra'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/user/', user_register, name='register_user'),
    path('register/mitra/', mitra_register, name='register_mitra'),
]

gunung/urls.py
from django.urls import path
from .views import home, daftar_gunung, detail_gunung


app_name = 'gunung'
urlpatterns = [
    path('', home, name='home'),
    path('gunung/', daftar_gunung, name='daftar'),
    path('gunung/<slug:slug>/', detail_gunung, name='detail'),
]

mountproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
        path('admin/', admin.site.urls),
        path('accounts/', include('accounts.urls')),
        path('', include('gunung.urls')),
        path('ckeditor/', include('ckeditor_uploader.urls')),
        path('toko/', include('toko.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toko/urls.py
from django.urls import path
from . import views

app_name='toko'
urlpatterns = [
    path('temukan/', views.toko_leaflet_page, name='toko_leaflet_page'),
    # path('terdekat/', views.toko_terdekat, name='toko_terdekat_api'),
    path('tambah/', views.tambah_toko, name='tambah_toko'),
    path('cari/', views.cari_toko, name='cari_toko'),
    path('dashboard/', views.dashboard_mitra, name='dashboard_mitra'),
    path('produk/tambah/', views.tambah_produk, name='tambah_produk'),
    path('produk/edit/<int:pk>/', views.edit_produk, name='edit_produk'),
    path('produk/hapus/<int:pk>/', views.hapus_produk, name='hapus_produk'),
    path('toko/<int:pk>/', views.detail_toko, name='detail_toko'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
  <script src="https://cdn.tailwindcss.com/3.4.16?plugins=typography@0.5.15"></script>
</head>
{% block extra_scripts %}{% endblock %}
<body>
{% include "navbar.html" %}
{% block content %}
<!-- konten halaman -->
{% endblock %}

</body>
</html>

templates/navbar.html
<nav style="background: #f8f8f8; padding: 1rem; display: flex; justify-content: space-between; align-items: center;">
  <div>
    <a href="{% url 'gunung:home' %}"><strong>🏕️ Mount Rent</strong></a>
  </div>

  <div>
    {% if user.is_authenticated %}
      <span style="margin-right: 1rem;">
        👤 {{ user.username }} ({{ user.role|capfirst }})
      </span>

      {% if user.role == 'mitra' %}
        <a href="{% url 'toko:dashboard_mitra' %}" style="margin-right: 1rem;">📦 Dashboard Mitra</a>
        <a href="{% url 'toko:tambah_produk' %}" style="margin-right: 1rem;">➕ Tambah Produk</a>

      {% endif %}

      <a href="{% url 'accounts:logout' %}" style="margin-right: 1rem;">🔓 Logout</a>
      <a href="{% url 'gunung:daftar' %}" style="margin-right: 1rem;">🏕️ daftar gunung</a>
      <a href="{% url 'toko:toko_leaflet_page' %}"><strong>🏕️ Cari Toko</strong></a>
    {% else %}
      <a href="{% url 'accounts:login_user' %}" style="margin-right: 1rem;">🔒 Login user</a>
      <a href="{% url 'accounts:login_mitra' %}" style="margin-right: 1rem;">🔒 Login mitra</a>
      <a href="{% url 'accounts:register_user' %}" style="margin-right: 0.5rem;">📝 Daftar User</a>
      <a href="{% url 'accounts:register_mitra' %}">📝 Daftar Mitra</a>
    {% endif %}
  </div>
</nav>